meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: docker_broker_images_leader_z1
    templates:
    - name: docker-broker-images
      release: docker-broker-images
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    properties: {}
  - name: docker_broker_images_z1
    templates:
    - name: docker-broker-images
      release: docker-broker-images
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    update:
      canaries: 10
    properties:
      docker_broker_images:
        leader_address: (( merge ))

networks: (( merge ))

properties: {}
